name: Deployment for Dockercompose app
on: 
  push:
    branches:
    - deploy
jobs:
  deployment-jobs:
    runs-on: self-hosted
    steps:
      - name: say hello
        run: echo "hello ma"
  
      - name: checkout of repo
        uses: actions/checkout@v6

      - name: build the docker image
        run: sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/discussions4:latest .

      - name: login to Docker hub 
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: push the docker image
        run: sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/discussions4:latest
